Item.create(name:"ジーパン", text: "中古品ですが、保存状態は良いです！", image: "https://www.gap.co.jp/webcontent/0016/185/365/cn16185365.jpg", price: 6000)
Item.create(name:"Tシャツ", text: "購入したのですが、使用していないので、新品同様です。", image: "https://www.prismacreative.jp/images/printable/tshirts/dalluc_dm501/DM501.png", price: 1500)
Item.create(name:"靴下", text: "以前年末セールに買った靴下です", image: "http://img21.shop-pro.jp/PA01352/163/product/105051367.jpg?cmsp_timestamp=20160721192907", price: 500)
Item.create(name:"シューズ", text: "通信販売で購入したのですが、サイズを間違えて購入してしまいました。", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjyrzDMV0mUXH4Fp8XtByEWaHag66Q7xEQP9_QKa42oddH6rmETA", price: 3000)

lady = Category.create(name: "レディース")
mens = Category.create(name: "メンズ")
Category.create(name: "ベビー・キッズ")
Category.create(name: "インテリア・住まい・小物")
Category.create(name: "本・音楽・ゲーム")
Category.create(name: "おもちゃ・ホビー・グッズ")
Category.create(name: "コスメ・香水・美容")
Category.create(name: "家電・スマホ・カメラ")
Category.create(name: "スポーツ・レジャー")
Category.create(name: "ハンドメイド")
Category.create(name: "チケット")
Category.create(name: "自動車・オートバイ")
Category.create(name: "その他")

mens.children.create(name: "トップス")
mens.children.create(name: "ジャケット/アウター")
mens.children.create(name: "パンツ")
mens.children.create(name: "靴")
mens.children.create(name: "バック")
mens.children.create(name: "スーツ")
mens.children.create(name: "帽子")
mens.children.create(name: "アクセサリー")
mens.children.create(name: "小物")
mens.children.create(name: "時計")
mens.children.create(name: "レッグウェア")
mens.children.create(name: "アンダーウェア")
mens.children.create(name: "パンツ")
mens.children.create(name: "その他")

lady.children.create(name: "トップス")
lady.children.create(name: "ジャケット/アウター")
lady.children.create(name: "パンツ")
lady.children.create(name: "スカート")
lady.children.create(name: "ワンピース")
lady.children.create(name: "靴")
lady.children.create(name: "ルームウェア/パジャマ")
lady.children.create(name: "レッグウェア")
lady.children.create(name: "帽子")
lady.children.create(name: "トップス")
lady.children.create(name: "ジャケット/アウター")
lady.children.create(name: "パンツ")